akka {
    loglevel = DEBUG
    loggers = ["Akka.Event.DefaultLogger"]
    stdout-loglevel = DEBUG

    actor {
        debug {
            receive = on
            lifecycle = on
            unhandled = on
        }
    }
}
